DROP TABLE MENUS CASCADE CONSTRAINTS;
DROP TABLE PLATILLOS CASCADE CONSTRAINTS;
DROP TABLE TIPO_INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE MENU_PLATILLOS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES_PLATILLOS CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_MENU CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_PLATILLO CASCADE CONSTRAINTS;



--Tabla para testear priocedimientos
CREATE TABLE PRODUCTOS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50),
    precio NUMBER(8)
);

-- Inserts de productos de supermercado (Líder / Walmart)
INSERT INTO PRODUCTOS VALUES (1, 'Leche Entera Soprole 1L', 1290);
INSERT INTO PRODUCTOS VALUES (2, 'Pan de Molde Ideal Blanco 700g', 1990);
INSERT INTO PRODUCTOS VALUES (3, 'Arroz Tucapel Grano Largo 1kg', 1690);
INSERT INTO PRODUCTOS VALUES (4, 'Aceite Maravilla Chef 1L', 2890);
INSERT INTO PRODUCTOS VALUES (5, 'Azúcar Iansa 1kg', 1390);
INSERT INTO PRODUCTOS VALUES (6, 'Harina Selecta sin Polvos 1kg', 1590);
INSERT INTO PRODUCTOS VALUES (7, 'Café Nescafé Tradición 170g', 5990);
INSERT INTO PRODUCTOS VALUES (8, 'Té Supremo 100 bolsas', 2990);
INSERT INTO PRODUCTOS VALUES (9, 'Mantequilla Soprole 250g', 3290);
INSERT INTO PRODUCTOS VALUES (10, 'Yoghurt Batido Colún 125g', 490);
INSERT INTO PRODUCTOS VALUES (11, 'Queso Gauda Colún 1kg', 10990);
INSERT INTO PRODUCTOS VALUES (12, 'Atún Lomitos San José 170g', 2490);
INSERT INTO PRODUCTOS VALUES (13, 'Papel Higiénico Elite 18x30m', 8990);
INSERT INTO PRODUCTOS VALUES (14, 'Detergente Ariel 3L', 9490);
INSERT INTO PRODUCTOS VALUES (15, 'Lavaloza Quix Limón 750ml', 2590);
INSERT INTO PRODUCTOS VALUES (16, 'Shampoo Pantene Hidratación 400ml', 5690);
INSERT INTO PRODUCTOS VALUES (17, 'Desodorante Dove Spray 150ml', 4290);
INSERT INTO PRODUCTOS VALUES (18, 'Cepillo de Dientes Colgate', 1990);
INSERT INTO PRODUCTOS VALUES (19, 'Pasta Dental Colgate Triple Acción 90g', 2590);
INSERT INTO PRODUCTOS VALUES (20, 'Galletas Tritón 126g', 1290);
INSERT INTO PRODUCTOS VALUES (21, 'Cereal Chocapic Nestlé 500g', 4790);
INSERT INTO PRODUCTOS VALUES (22, 'Mermelada Watts Frutilla 500g', 2890);
INSERT INTO PRODUCTOS VALUES (23, 'Jugo Watts Durazno 1L', 1690);
INSERT INTO PRODUCTOS VALUES (24, 'Coca-Cola Original 1.5L', 2190);
INSERT INTO PRODUCTOS VALUES (25, 'Agua Mineral Benedictino 1.6L', 1290);
INSERT INTO PRODUCTOS VALUES (26, 'Cerveza Cristal 1L', 1990);
INSERT INTO PRODUCTOS VALUES (27, 'Vino Gato Negro Cabernet 750ml', 4490);
INSERT INTO PRODUCTOS VALUES (28, 'Papas Fritas Lays Clásicas 145g', 2890);
INSERT INTO PRODUCTOS VALUES (29, 'Helado Savory 1L Vainilla', 4990);
INSERT INTO PRODUCTOS VALUES (30, 'Huevos de Gallina 12u', 3890);

COMMIT;


--Creamos tabla menu

CREATE TABLE MENUS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

--Creamos la tabla
CREATE TABLE PLATILLOS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

--Crear la tabla para auditar el platillo
CREATE TABLE AUDITORIA_PLATILLO(
    id NUMBER PRIMARY KEY,
    id_platillo NUMBER,
    nombre_antiguo VARCHAR2(50),
    nombre_nuevo VARCHAR2(50),
    accion VARCHAR(10) NOT NULL,
    fecha TIMESTAMP,
    usuario VARCHAR(20),
    FOREIGN KEY (id_platillo) REFERENCES PLATILLOS(id)
);

--CREAMOS LA TABLA TIPO_INGREDIENTES
CREATE TABLE TIPO_INGREDIENTES(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

--Ahora vamos con las tablas pivotes o las relaciones 1 n

--Vamos con la tabla que tiene relacion 1 n
CREATE TABLE INGREDIENTES(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    id_tipo_ingrediente NUMBER,
    FOREIGN KEY (id_tipo_ingrediente) REFERENCES TIPO_INGREDIENTES(id)
);

--CREAMOS LA TABLA PIVOTE
CREATE TABLE MENU_PLATILLOS(
    id_menu NUMBER,
    id_platillo NUMBER,
    PRIMARY KEY (id_menu, id_platillo),
    FOREIGN KEY (id_menu) REFERENCES MENUS(id),
    FOREIGN KEY (id_platillo) REFERENCES PLATILLOS(id)
);

CREATE TABLE INGREDIENTES_PLATILLOS(
    id_ingrediente NUMBER,
    id_platillo NUMBER,
    PRIMARY KEY (id_ingrediente, id_platillo),
    FOREIGN KEY (id_ingrediente) REFERENCES INGREDIENTES(id),
    FOREIGN KEY (id_platillo) REFERENCES PLATILLOS(id)
);

COMMIT;


--CREAREMOS EL TRIGGER PARA AUDITAR LOS MENUS

CREATE TABLE AUDITORIA_MENU(
    id NUMBER PRIMARY KEY,
    id_menu NUMBER,
    tipo_accion VARCHAR2(20),
    valor_antiguo VARCHAR2(50),
    valor_nuevo VARCHAR2(50),
    fecha DATE,
    usuario VARCHAR(50),
    FOREIGN KEY (id_menu) REFERENCES MENUS(id)
);

--CREEMOS EL TRIGGER PARA PODER AUDITAR LA INSERCION DE UN NUEVO MENU

CREATE SEQUENCE seq_menus START WITH 1 INCREMENT by 1; 

CREATE OR REPLACE TRIGGER trg_auditar_menu
    AFTER INSERT ON MENUS
        FOR EACH ROW
            BEGIN
                INSERT INTO AUDITORIA_MENU(id, ID_MENU, TIPO_ACCION, valor_antiguo, valor_nuevo, FECHA, USUARIO) VALUES(seq_menus.NEXTVAL, :NEW.id, 'INSERT', :OLD.nombre, :NEW.nombre, SYSDATE, USER);
            END;
            /


--Simulemos que el trigger se dispara
INSERT INTO MENUS(id, NOMBRE) VALUES(1, 'POLLO A LA PLANCHA');
INSERT INTO MENUS(id, NOMBRE) VALUES(2, 'ESPAGUETI');
INSERT INTO MENUS(id, NOMBRE) VALUES(3, 'CARNECITA');

COMMIT;


--CREEMOS UN TRIGGER QUE SE EJECUTE CUANDO UN MENU SE MODIFICA

CREATE OR REPLACE TRIGGER trg_auditar_update_menu
    AFTER UPDATE ON MENUS
        FOR EACH ROW
            BEGIN
                INSERT INTO AUDITORIA_MENU(id, ID_MENU, TIPO_ACCION, valor_antiguo, valor_nuevo, FECHA, USUARIO)
                VALUES (seq_menus.NEXTVAL, :NEW.id, 'UPDATE', :OLD.nombre, :NEW.nombre, SYSDATE, USER );
            END;
            /

--SIMULAMOS LA ACTUALIZACIÖN
UPDATE MENUS
SET nombre = 'CHORILLANA' 
WHERE id = 1;
COMMIT;







CREATE SEQUENCE seq_uno_uno START WITH 1 INCREMENT by 1; 

CREATE OR REPLACE TRIGGER trg_auditar_platillo_insert
    AFTER INSERT ON  PLATILLOS
        FOR EACH ROW
            BEGIN
                INSERT INTO AUDITORIA_PLATILLO(id, ID_PLATILLO, NOMBRE_ANTIGUO, NOMBRE_NUEVO, accion, fecha, usuario) VALUES(seq_uno_uno.NEXTVAL, :NEW.id, :NEW.nombre, :new.nombre, 'INSERT', SYSTIMESTAMP, USER);
            END;
            /

--Ara deetctar actualizaciones del suhi
CREATE OR REPLACE TRIGGER trg_auditar_platillo_update
    AFTER UPDATE ON PLATILLOS
        FOR EACH ROW
            BEGIN
                INSERT INTO AUDITORIA_PLATILLO(id, ID_PLATILLO, NOMBRE_ANTIGUO, NOMBRE_NUEVO, accion, fecha, usuario) VALUES (seq_uno_uno.NEXTVAL, :OLD.id, :OLD.nombre, :new.nombre, 'UPDATE', SYSTIMESTAMP, USER);
            END;
            /

INSERT INTO PLATILLOS(id, nombre) VALUES (1, 'SUSHI');
COMMIT;

UPDATE PLATILLOS
SET nombre = 'Sushi saludable 0 azucar' 
WHERE id = 1;
COMMIT; 


--CREAREMOS UN PROCEDIMIENTO QUE ACTUALICE EL PRECIO DE LOS PRODUCTOS

CREATE OR REPLACE PROCEDURE pr_ofertas_del_día
    IS
        BEGIN
            UPDATE PRODUCTOS SET PRECIO = PRECIO - (PRECIO * 0.05);
        END;
        /

EXEC pr_ofertas_del_día;

SELECT * FROM PRODUCTOS;